edge-ai-void-detection/modules/apiserver/src/RetailDemo.Web.Api/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace RetailDemo.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

edge-ai-void-detection/modules/apiserver/src/RetailDemo.Web.Api/Controllers/ToolsController.cs
using RetailDemo.Core;
using RetailDemo.Core.Entities;
using RetailDemo.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace RetailDemo.Web.Controllers
{
    public class ToolsController : Controller
    {
        private readonly IRepository _repository;

        public ToolsController(IRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var items = _repository.List<ImageEvent>();
            return View(items);
        }

        public IActionResult Populate()
        {
            int recordsAdded = DatabasePopulator.PopulateImageEventsDatabase(_repository);
            int recordsAddedEdgeDevices = DatabasePopulator.PopulateEdgeDevicesDatabase(_repository);
            return Ok(recordsAdded);
        }
    }
}

edge-ai-void-detection/modules/apiserver/src/RetailDemo.Web.Api/Pages/ToolsRazorPage/Index.cshtml.cs
using RetailDemo.Core.Entities;
using RetailDemo.Core.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace RetailDemo.Web.Pages.ToDoRazorPage
{
    public class IndexModel : PageModel
    {
        private readonly IRepository _repository;

        public List<ImageEvent> ImageEventItems { get; set; }

        public IndexModel(IRepository repository)
        {
            _repository = repository;
        }

        public void OnGet()
        {
            ImageEventItems = _repository.List<ImageEvent>();
        }
    }
}

edge-ai-void-detection/modules/apiserver/src/RetailDemo.Web.Api/Pages/ToolsRazorPage/Populate.cshtml.cs
using RetailDemo.Core;
using RetailDemo.Core.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RetailDemo.Web.Pages.ToDoRazorPage
{
    public class PopulateModel : PageModel
    {
        private readonly IRepository _repository;

        public PopulateModel(IRepository repository)
        {
            _repository = repository;
        }

        public int RecordsAdded { get; set; }

        public void OnGet()
        {
            RecordsAdded = DatabasePopulator.PopulateEdgeDevicesDatabase(_repository);
            RecordsAdded = DatabasePopulator.PopulateImageEventsDatabase(_repository);
        }
    }
}

edge-ai-void-detection/modules/apiserver/src/RetailDemo.Web.Api/Pages/ToolsRazorPage/Index.cshtml
@page
@model RetailDemo.Web.Pages.ToDoRazorPage.IndexModel

<h2>Retail Demo Tools</h2>
<ul>
    @foreach (var item in Model.ImageEventItems)
    {
    <li>@item.EdgeDeviceName<br />@item.CaptureTime<br />@item.Body.Dest_img</li>
    }
</ul>

edge-ai-void-detection/modules/apiserver/src/RetailDemo.Web.Api/Pages/ToolsRazorPage/Populate.cshtml
@page
@model RetailDemo.Web.Pages.ToDoRazorPage.PopulateModel
<h3>Records Added: @Model.RecordsAdded</h3>
<p>
    <a asp-page="Index">Check them out!</a>
</p>

edge-ai-void-detection/modules/apiserver/src/RetailDemo.Web.Api/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Clean DDD Architecture Sample";
}

<div class="row">
    <div class="col-md-6">
        <h2>Retail Demo Tools</h2>
        <ul>
            <li><a asp-area="" asp-controller="Tools" asp-action="Populate">Load Sample Data</a> (API call returning just a number)</li>
            <li><a href="/swagger">API Documentation (Swagger)</a></li>
        </ul>
        <h2>Retail Demo Tools using Razor Pages</h2>
        <ul>
            <li><a asp-page="/ToolsRazorPage/Populate">Load Sample Data Option 2</a></li>
        </ul>
    </div>
    <div class="col-md-6">
        <h2>About Retail Demo</h2>
        <ul>
            <li><a href="https://github.com">GitHub for this code</a></li>
        </ul>
    </div>
</div>

edge-ai-void-detection/modules/apiserver/src/RetailDemo.Web.Api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RetailDemo.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RetailDemo.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - RetailDemo.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

@await RenderSectionAsync("scripts", required: false).ConfigureAwait(false)
</body>
</html>

edge-ai-void-detection/modules/apiserver/src/RetailDemo.Web.Api/Views/Tools/Index.cshtml
@{
    ViewData["Title"] = "Items List";
}
@model IEnumerable<RetailDemo.Core.Entities.ImageEvent>
<h2>To Do Items (MVC View)</h2>
<ul>
@foreach (var item in Model)
{
    <li>@item.EdgeDeviceName<br />@item.CaptureTime<br />@item.Body.Dest_img</li>
}
</ul>